# docker compose up -d
# psql -h localhost -p 5432 -U <DB_USER> -d <DB_NAME>
# \i setup.sh
# docker compose down
# rm -rf dbdata
version: '3.8'

services:
  db:
    image: postgres:latest
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - ./dbdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
