# docker compose up -d
# psql -h localhost -p 5432 -U postgres
# \i setup.sh
version: '3.8'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: rankings
      POSTGRES_USER: norman
      POSTGRES_PASSWORD: password
    volumes:
      - ./dbdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
