INSERT INTO Watching VALUES ('njchen', 362466) ON CONFLICT DO NOTHING RETURNING *;

INSERT INTO Watching VALUES ('njchen', 362466) ON CONFLICT DO NOTHING RETURNING *;

DELETE FROM Watching WHERE uID = 'njchen' AND jID = 362466;
