BEGIN;
DROP TRIGGER IF EXISTS delete_unsuccessful_contributions_trigger ON Contributions CASCADE;
DROP TRIGGER IF EXISTS stage_single_row_trigger ON Stage CASCADE;
DROP TRIGGER IF EXISTS year_single_row_trigger ON Year CASCADE;
DROP TRIGGER IF EXISTS season_single_row_trigger ON Season CASCADE;
DROP TRIGGER IF EXISTS cycle_single_row_trigger ON Cycle CASCADE;
DROP TRIGGER IF EXISTS log_contribution_change_trigger ON Contributions CASCADE;

DROP TABLE IF EXISTS Jobs CASCADE;
DROP TABLE IF EXISTS Users CASCADE;
DROP TABLE IF EXISTS Admins CASCADE;
DROP TABLE IF EXISTS Watching CASCADE;
DROP TABLE IF EXISTS Contributions CASCADE;
DROP TABLE IF EXISTS Tags CASCADE;
DROP TABLE IF EXISTS Rankings CASCADE;
DROP TABLE IF EXISTS Stage CASCADE;
DROP TABLE IF EXISTS Year CASCADE;
DROP TABLE IF EXISTS Season CASCADE;
DROP TABLE IF EXISTS Cycle CASCADE;
DROP TABLE IF EXISTS ContributionsLogs CASCADE;

DROP TYPE IF EXISTS SeasonEnum CASCADE;
DROP TYPE IF EXISTS EmployerRankingEnum CASCADE;
DROP TYPE IF EXISTS DifficultyEnum CASCADE;
DROP TYPE IF EXISTS LengthEnum CASCADE;
DROP TYPE IF EXISTS VibeEnum CASCADE;
DROP TYPE IF EXISTS TechnicalEnum CASCADE;
COMMIT;
