DROP TABLE IF EXISTS Rankings;

DROP TABLE IF EXISTS Contributions;

DROP TABLE IF EXISTS Watching;

DROP TABLE IF EXISTS Admins;

DROP TABLE IF EXISTS Users;

DROP TABLE IF EXISTS Jobs;

DROP TABLE IF EXISTS Stage;